services:
- type: web
  name: <PROJECTNAME>
  env: node
  branch: main
  startCommand: node .output/server/index.mjs
  buildCommand: yarn; yarn build
  envVars:
  - key: NITRO_PRESET
    value: render-com